### PR TITLE
Added AVG TTL of database info

### PR DESCRIPTION
**Pull request by mantico91**
perf: Added Average TTL into parsing databases info. Lines: 70 and 77.

### CODE REVIEW

**Review by FGRibreau — CHANGES_REQUESTED** [review]
Could you please also update the test suite?

**Comment by mantico91** [comment]
> Could you please also update the test suite?

Thank you. It's the first time for me. I hope i made it in the right way. Let me know.

**Comment by FGRibreau** [comment]
@mantico91 thanks but I do not see the update tests :)
The file is here https://github.com/FGRibreau/node-redis-info/blob/master/test/redis-info.test.js and you would want to add some tests to ensure :
- `expires` and/or `avg_ttl` are parsed when they exist
- when `expires` and/or `avg_ttl` do not exist, the program does not fail (attribute values are empty)

**Comment by mantico91** [comment]
I'm stupid. I created two more branches, sorry. I tried with "mocha" and everything went fine. Am i right?
See the screenshot.

image

**Comment by FGRibreau** [comment]
@mantico91 thx! released in v3.1.0 :+1:

**Comment by mantico91** [comment]
> @mantico91 thx! released in v3.1.0 👍

Thank to you!

**Pull request merged**
